/*
 * This file is part of the SILC project (http://www.silc.de)
 *
 * Copyright (c) 2009-2011,
 *    RWTH Aachen, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


#include <config.h>

#include "SILC_Fmpi.h"
#include "config.h"

/**
 * @file  SILC_Fmpi_Env.c
 * @maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 * @status     ALPHA
 * @ingroup    MPI_Wrapper
 *
 * @brief Fortran interface wrappers for environmental management
 */

/* uppercase defines */
/** @def MPI_Init_thread_U
    Exchange MPI_Init_thread_U by MPI_INIT_THREAD.
    It is used for the Fortran wrappers of me).
 */
#define MPI_Init_thread_U MPI_INIT_THREAD


/** @def MPI_Finalize_U
    Exchange MPI_Finalize_U by MPI_FINALIZE.
    It is used for the Fortran wrappers of me).
 */
#define MPI_Finalize_U MPI_FINALIZE

/** @def MPI_Finalized_U
    Exchange MPI_Finalized_U by MPI_FINALIZED.
    It is used for the Fortran wrappers of me).
 */
#define MPI_Finalized_U MPI_FINALIZED

/** @def MPI_Init_U
    Exchange MPI_Init_U by MPI_INIT.
    It is used for the Fortran wrappers of me).
 */
#define MPI_Init_U MPI_INIT

/** @def MPI_Initialized_U
    Exchange MPI_Initialized_U by MPI_INITIALIZED.
    It is used for the Fortran wrappers of me).
 */
#define MPI_Initialized_U MPI_INITIALIZED

/** @def MPI_Is_thread_main_U
    Exchange MPI_Is_thread_main_U by MPI_IS_THREAD_MAIN.
    It is used for the Fortran wrappers of me).
 */
#define MPI_Is_thread_main_U MPI_IS_THREAD_MAIN

/** @def MPI_Query_thread_U
    Exchange MPI_Query_thread_U by MPI_QUERY_THREAD.
    It is used for the Fortran wrappers of me).
 */
#define MPI_Query_thread_U MPI_QUERY_THREAD


/* lowercase defines */
/** @def MPI_Init_thread_L
    Exchanges MPI_Init_thread_L by mpi_init_thread.
    It is used for the Forran wrappers of me).
 */
#define MPI_Init_thread_L mpi_init_thread


/** @def MPI_Finalize_L
    Exchanges MPI_Finalize_L by mpi_finalize.
    It is used for the Forran wrappers of me).
 */
#define MPI_Finalize_L mpi_finalize

/** @def MPI_Finalized_L
    Exchanges MPI_Finalized_L by mpi_finalized.
    It is used for the Forran wrappers of me).
 */
#define MPI_Finalized_L mpi_finalized

/** @def MPI_Init_L
    Exchanges MPI_Init_L by mpi_init.
    It is used for the Forran wrappers of me).
 */
#define MPI_Init_L mpi_init

/** @def MPI_Initialized_L
    Exchanges MPI_Initialized_L by mpi_initialized.
    It is used for the Forran wrappers of me).
 */
#define MPI_Initialized_L mpi_initialized

/** @def MPI_Is_thread_main_L
    Exchanges MPI_Is_thread_main_L by mpi_is_thread_main.
    It is used for the Forran wrappers of me).
 */
#define MPI_Is_thread_main_L mpi_is_thread_main

/** @def MPI_Query_thread_L
    Exchanges MPI_Query_thread_L by mpi_query_thread.
    It is used for the Forran wrappers of me).
 */
#define MPI_Query_thread_L mpi_query_thread


/**
 * @name Fortran wrappers
 * @{
 */

#ifndef NEED_F2C_CONV

#if HAVE( DECL_PMPI_INITIALIZED ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Initialized )
/**
 * Measurement wrapper for MPI_Initialized
 * @note Auto-generated by wrapgen from template: SILC_Fmpi_Std.w
 * @note Fortran interface
 * @note Introduced with MPI-1
 * @ingroup env
 */
void
FSUB( MPI_Initialized )( int* flag,
                         int* ierr )
{
    *ierr = MPI_Initialized( flag );
}
#endif

/* If MPI_Comm_f2c is HAVE as a simple macro (which typically does nothing)
 * as it would require a "real" function if it is really needed
 * => we can save the f2c and c2s conversions */

#if HAVE( DECL_PMPI_INIT_THREAD )
/**
 * Measurement wrapper for MPI_Init_tread
 * @note Manually adapted wrapper
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 */
void
FSUB( MPI_Init_thread )( int* required,
                         int* provided,
                         int* ierr )
{
    *ierr = MPI_Init_thread( 0, ( char*** )0, *required, provided );
}
#endif

/**
 * Measurement wrapper for MPI_Init
 * @note Manually adapted wrapper
 * @note Fortran interface
 * @note Introduced with MPI-1
 * @ingroup env
 */
void
FSUB( MPI_Init )( int* ierr )
{
    *ierr = MPI_Init( 0, ( char*** )0 );
}

#if HAVE( DECL_PMPI_FINALIZE )
/**
 * Measurement wrapper for MPI_Finalize
 * @note Auto-generated by wrapgen from template: SILC_Fmpi_Std.w
 * @note Fortran interface
 * @note Introduced with MPI-1
 * @ingroup env
 */
void
FSUB( MPI_Finalize )( int* ierr )
{
    *ierr = MPI_Finalize();
}
#endif
#if HAVE( DECL_PMPI_FINALIZED ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Finalized )
/**
 * Measurement wrapper for MPI_Finalized
 * @note Auto-generated by wrapgen from template: SILC_Fmpi_Std.w
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 */
void
FSUB( MPI_Finalized )( int* flag,
                       int* ierr )
{
    *ierr = MPI_Finalized( flag );
}
#endif
#if HAVE( DECL_PMPI_IS_THREAD_MAIN ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Is_thread_main )
/**
 * Measurement wrapper for MPI_Is_thread_main
 * @note Auto-generated by wrapgen from template: SILC_Fmpi_Std.w
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 */
void
FSUB( MPI_Is_thread_main )( int* flag,
                            int* ierr )
{
    *ierr = MPI_Is_thread_main( flag );
}
#endif
#if HAVE( DECL_PMPI_QUERY_THREAD ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Query_thread )
/**
 * Measurement wrapper for MPI_Query_thread
 * @note Auto-generated by wrapgen from template: SILC_Fmpi_Std.w
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 */
void
FSUB( MPI_Query_thread )( int* provided,
                          int* ierr )
{
    *ierr = MPI_Query_thread( provided );
}
#endif

#else /* !NEED_F2C_CONV */

#if HAVE( DECL_PMPI_INIT_THREAD )
/**
 * Measurement wrapper for MPI_Init_tread
 * @note Manually adapted wrapper
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 */
void
FSUB( MPI_Init_thread )( int* required,
                         int* provided,
                         int* ierr )
{
    if ( sizeof( MPI_Fint ) != sizeof( int ) )
    {
        SILC_ERROR( SILC_ERROR_F2C_INT_SIZE_MISMATCH, "" );
    }
    *ierr = MPI_Init_thread( 0, ( char*** )0, *required, provided );
}
#endif

/**
 * Measurement wrapper for MPI_Init
 * @note Manually adapted wrapper
 * @note Fortran interface
 * @note Introduced with MPI-1
 * @ingroup env
 */
void
FSUB( MPI_Init )( int* ierr )
{
    if ( sizeof( MPI_Fint ) != sizeof( int ) )
    {
        SILC_ERROR( SILC_ERROR_F2C_INT_SIZE_MISMATCH, "" );
    }
    *ierr = MPI_Init( 0, ( char*** )0 );
}

#if HAVE( DECL_PMPI_FINALIZE )
/**
 * Measurement wrapper for MPI_Finalize
 * @note Auto-generated by wrapgen from template: f2c_c2f.w
 * @note Fortran interface
 * @note Introduced with MPI-1
 * @ingroup env
 * For the order of events see @ref MPI_Finalize
 */
void
FSUB( MPI_Finalize )( int* ierr )
{
    *ierr = MPI_Finalize();
}
#endif
#if HAVE( DECL_PMPI_FINALIZED ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Finalized )
/**
 * Measurement wrapper for MPI_Finalized
 * @note Auto-generated by wrapgen from template: f2c_c2f.w
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 * For the order of events see @ref MPI_Finalized
 */
void
FSUB( MPI_Finalized )( MPI_Fint* flag,
                       int*      ierr )
{
    *ierr = MPI_Finalized( flag );
}
#endif
#if HAVE( DECL_PMPI_IS_THREAD_MAIN ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Is_thread_main )
/**
 * Measurement wrapper for MPI_Is_thread_main
 * @note Auto-generated by wrapgen from template: f2c_c2f.w
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 * For the order of events see @ref MPI_Is_thread_main
 */
void
FSUB( MPI_Is_thread_main )( MPI_Fint* flag,
                            int*      ierr )
{
    *ierr = MPI_Is_thread_main( flag );
}
#endif
#if HAVE( DECL_PMPI_QUERY_THREAD ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Query_thread )
/**
 * Measurement wrapper for MPI_Query_thread
 * @note Auto-generated by wrapgen from template: f2c_c2f.w
 * @note Fortran interface
 * @note Introduced with MPI-2
 * @ingroup env
 * For the order of events see @ref MPI_Query_thread
 */
void
FSUB( MPI_Query_thread )( MPI_Fint* provided,
                          int*      ierr )
{
    *ierr = MPI_Query_thread( provided );
}
#endif

#if HAVE( DECL_PMPI_INITIALIZED ) && !defined( SILC_MPI_NO_EXTRA ) && !defined( SILC_MPI_NO_ENV ) && !defined( MPI_Initialized )
/**
 * Measurement wrapper for MPI_Initialized
 * @note Auto-generated by wrapgen from template: SILC_Fmpi_Std.w
 * @note Fortran interface
 * @note Introduced with MPI-1
 * @ingroup env
 */
void
FSUB( MPI_Initialized )( int* flag,
                         int* ierr )
{
    *ierr = MPI_Initialized( flag );
}
#endif

#endif

/**
 * @}
 */
