      INTEGER( KIND=8 ) :: pomp2_region_1
      INTEGER( KIND=8 ) :: pomp2_region_2
      INTEGER( KIND=8 ) :: pomp2_region_3
      integer pomp_get_max_threads1311763976775744
      integer ( kind=8 ) :: pomp2_old_task, pomp2_new_task 
      logical :: pomp_if 
      integer pomp_num_threads 
      common /cb1311763976775744/ pomp2_region_1,&
              pomp2_region_2,&
              pomp2_region_3
