/*
 * This file is part of the Score-P software (http://www.score-p.org)
 *
 * Copyright (c) 2009-2012,
 *    RWTH Aachen University, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene, USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    German Research School for Simulation Sciences GmbH, Juelich/Aachen, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */

/**
 * @status     alpha
 * @file       scorep_compiler_gnu.c
 * @maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 *
 * @brief Support for GNU-Compiler
 * Will be triggered by the '-finstrument-functions' flag of the GNU
 * compiler.
 */

#include <config.h>
#include <stdio.h>
#include <unistd.h>

#include <UTILS_Debug.h>

#include <SCOREP_Types.h>
#include <SCOREP_Location.h>
#include <SCOREP_Events.h>
#include <SCOREP_RuntimeManagement.h>
#include <SCOREP_Mutex.h>

#include "SCOREP_Compiler_Init.h"
#include "scorep_compiler_data.h"
#include "scorep_compiler_symbol_table.h"


/**
 * static variable to control initialize status of GNU
 */
static bool scorep_compiler_initialized = false;

/**
 * flag that indicates whether the GNU compiler adapter was finalized
 */
static bool scorep_compiler_finalized = false;

/**
 * Mutex for exclusive access to the region hash table.
 */
static SCOREP_Mutex scorep_compiler_region_mutex;

/* ***************************************************************************************
   Implementation of functions called by compiler instrumentation
*****************************************************************************************/

/**
 * @brief This function is called just after the entry of a function
 * generated by the GNU compiler.
 * @param func      The address of the start of the current function.
 * @param callsice  The call site of the current function.
 */
void
__cyg_profile_func_enter( void* func,
                          void* callsite )
{
    scorep_compiler_hash_node* hash_node;

    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "call function enter." );

    /*
     * put hash table entries via mechanism for bfd symbol table
     * to calculate function addresses if measurement was not initialized
     */

    if ( !scorep_compiler_initialized )
    {
        if ( scorep_compiler_finalized )
        {
            return;
        }

        /* not initialized so far */
        SCOREP_InitMeasurement();
    }

    /* On ARM platform the 0-bit indicates whether it is thumb code or arm code.
       Thus, thumb code address differ from the real function address that we
       get from libbfd or nm by 1 */
#if HAVE( PLATFORM_ARM )
    /* Clear least significant bit */
    func = ( void* )( ( ( long )func | 1 ) - 1 );
#endif

    if ( ( hash_node = scorep_compiler_hash_get( ( long )func ) ) )
    {
        if ( hash_node->region_handle == SCOREP_INVALID_REGION )
        {
            SCOREP_MutexLock( scorep_compiler_region_mutex );
            if ( hash_node->region_handle == SCOREP_INVALID_REGION )
            {
                /* -- region entered the first time, register region -- */
                scorep_compiler_register_region( hash_node );
            }
            SCOREP_MutexUnlock( scorep_compiler_region_mutex );
        }
        UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER,
                            "enter the region with address %p",
                            func );
        SCOREP_EnterRegion( hash_node->region_handle );
    }
}

/**
 * @brief This function is called just before the exit of a function
 * generated by the GNU compiler.
 * @param func      The address of the end of the current function.
 * @param callsice  The call site of the current function.
 */
void
__cyg_profile_func_exit( void* func,
                         void* callsite )
{
    if ( scorep_compiler_finalized )
    {
        return;
    }

    /* On ARM platform the 0-bit indicates whether it is thumb code or arm code.
       Thus, thumb code address differ from the real function address that we
       get from libbfd or nm by 1 */
#if HAVE( PLATFORM_ARM )
    /* Clear least significant bit */
    func = ( void* )( ( ( long )func | 1 ) - 1 );
#endif

    scorep_compiler_hash_node* hash_node;
    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "call function exit." );
    if ( ( hash_node = scorep_compiler_hash_get( ( long )func ) ) )
    {
        UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER,
                            "exit the region with address %p",
                            func );
        SCOREP_ExitRegion( hash_node->region_handle );
    }
}

/* ***************************************************************************************
   Adapter management
*****************************************************************************************/

SCOREP_ErrorCode
scorep_compiler_init_adapter( void )
{
    if ( !scorep_compiler_initialized )
    {
        UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, " inititialize GNU compiler adapter." );

        /* Initialize region mutex */
        SCOREP_MutexCreate( &scorep_compiler_region_mutex );

        /* Initialize hash tables */
        scorep_compiler_hash_init();

        /* call function to calculate symbol table */
        scorep_compiler_get_sym_tab();

        /* Sez flag */
        scorep_compiler_initialized = true;

        UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER,
                            " inititialization of GNU compiler adapter done." );
    }

    return SCOREP_SUCCESS;
}

SCOREP_ErrorCode
scorep_compiler_init_location( SCOREP_Location* locationData )
{
    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "GNU compiler adapter init location!" );
    return SCOREP_SUCCESS;
}

/* Adapter finalization */
void
scorep_compiler_finalize( void )
{
    /* call only, if previously initialized */
    if ( scorep_compiler_initialized )
    {
        /* Delete hash table */
        scorep_compiler_hash_free();

        /* Set initialization flag */
        scorep_compiler_initialized = false;
        scorep_compiler_finalized   = true;
        UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, " finalize GNU compiler adapter." );

        /* Delete region mutex */
        SCOREP_MutexDestroy( &scorep_compiler_region_mutex );
    }
}
