/*
 * This file is part of the Score-P software (http://www.score-p.org)
 *
 * Copyright (c) 2009-2012,
 * RWTH Aachen University, Germany
 *
 * Copyright (c) 2009-2012,
 * Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *
 * Copyright (c) 2009-2012,
 * Technische Universitaet Dresden, Germany
 *
 * Copyright (c) 2009-2012,
 * University of Oregon, Eugene, USA
 *
 * Copyright (c) 2009-2013,
 * Forschungszentrum Juelich GmbH, Germany
 *
 * Copyright (c) 2009-2012,
 * German Research School for Simulation Sciences GmbH, Juelich/Aachen, Germany
 *
 * Copyright (c) 2009-2012,
 * Technische Universitaet Muenchen, Germany
 *
 * This software may be modified and distributed under the terms of
 * a BSD-style license.  See the COPYING file in the package base
 * directory for details.
 */

/**
 * @status     alpha
 * @file       src/adapters/compiler/scorep_compiler_sun.c
 * @maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 *
 * @brief SUN f90 compiler PHAT interface.
 * Compiler adapter for the SUN F90 compiler.
 */

#include <config.h>
#include <stdlib.h>

#include <SCOREP_Types.h>
#include <UTILS_Error.h>
#include <UTILS_Debug.h>
#include <SCOREP_Events.h>
#include <SCOREP_Definitions.h>
#include <SCOREP_RuntimeManagement.h>
#include <SCOREP_Mutex.h>

#include "SCOREP_Compiler_Init.h"
#include "scorep_compiler_sun_data.h"


/**
 * This function is called at the entry of each function
 * The call is generated by the SUN f90 compilers
 */
void
phat_enter( char* name,
            int*  id )
{
    if ( !scorep_compiler_initialized )
    {
        if ( scorep_compiler_finalized )
        {
            return;
        }
        SCOREP_InitMeasurement();
    }

    if ( *id == SCOREP_INVALID_REGION )
    {
        /* region entered the first time, register region */
        SCOREP_MutexLock( scorep_compiler_region_mutex );
        if ( *id == SCOREP_INVALID_REGION )
        {
            *id = scorep_compiler_register_region( name );
        }
        SCOREP_MutexUnlock( scorep_compiler_region_mutex );
    }

    if ( *id != SCOREP_FILTERED_REGION )
    {
        SCOREP_EnterRegion( *id );
    }
}


/**
 * This function is called at the exit of each function
 * The call is generated by the SUN F90 compilers
 */
void
phat_exit( char* name,
           int*  id )
{
    if ( scorep_compiler_finalized )
    {
        return;
    }

    if ( ( *id != SCOREP_INVALID_REGION ) && ( *id != SCOREP_FILTERED_REGION ) )
    {
        SCOREP_ExitRegion( *id );
    }
}
