/*
 * This file is part of the Score-P software (http://www.score-p.org)
 *
 * Copyright (c) 2009-2012,
 *    RWTH Aachen University, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene, USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    German Research School for Simulation Sciences GmbH, Juelich/Aachen, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


/**
 * @status     alpha
 * @file       scorep_compiler_ftrace.c
 * @maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 *
 * @brief Compiler adapter version for NEC SX compiler
 */

#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include <UTILS_Debug.h>
#include <SCOREP_Location.h>
#include <SCOREP_Events.h>
#include <SCOREP_Definitions.h>
#include <SCOREP_RuntimeManagement.h>
#include <SCOREP_Mutex.h>
#include <SCOREP_Filter.h>

#include <SCOREP_Compiler_Init.h>
#include <scorep_compiler_data.h>


extern void*
scorep_ftrace_getname( void );
extern int
scorep_ftrace_getname_len( void );


static uint32_t scorep_compiler_initialize = 1;

static uint32_t scorep_compiler_finalized = 0;

/**
 * Mutex for exclusive access to the region hash table.
 */
static SCOREP_Mutex scorep_compiler_region_mutex;


void
_ftrace_enter2_( void );
void
_ftrace_exit2_( void );
void
_ftrace_stop2_( void );

/*
 * This function is called at the entry of each function
 * The call is generated by the NEC SX compilers
 */

void
_ftrace_enter2_( void )
{
    char* region_name = scorep_ftrace_getname();
    int   name_len    = scorep_ftrace_getname_len();

    scorep_compiler_hash_node* hash_node = scorep_compiler_hash_get( ( long )region_name );

    if ( scorep_compiler_initialize )
    {
        if ( scorep_compiler_finalized )
        {
            return;
        }

        /* not initialized so far */
        SCOREP_InitMeasurement();
    }

    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "function name: %s", region_name );
    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "function length: %i", name_len );

    if ( !hash_node )
    {
        scorep_compiler_hash_put( ( long )region_name, region_name, region_name, "", name_len );
    }

    if ( ( hash_node = scorep_compiler_hash_get( ( long )region_name ) ) )
    {
        if ( hash_node->region_handle == SCOREP_INVALID_REGION )
        {
            SCOREP_MutexLock( scorep_compiler_region_mutex );
            if ( hash_node->region_handle == SCOREP_INVALID_REGION )
            {
                /* Check for filtered regions */
                if ( ( strncmp( region_name, "POMP", 4 ) == 0 ) ||
                     ( strncmp( region_name, "Pomp", 4 ) == 0 ) ||
                     ( strncmp( region_name, "pomp", 4 ) == 0 ) ||
                     SCOREP_Filter_Match( NULL, region_name, NULL ) )
                {
                    hash_node->region_handle = SCOREP_FILTERED_REGION;
                }

                /* Region entered the first time, register region */
                else
                {
                    scorep_compiler_register_region( hash_node );
                    assert( hash_node->region_handle != SCOREP_FILTERED_REGION );
                    assert( hash_node->region_handle != SCOREP_INVALID_REGION );
                }
            }
            SCOREP_MutexUnlock( scorep_compiler_region_mutex );
        }
        if ( hash_node->region_handle != SCOREP_FILTERED_REGION )
        {
            UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER,
                                "enter the region with handle %i",
                                hash_node->region_handle );
            SCOREP_EnterRegion( hash_node->region_handle );
        }
    }
}


/*
 * This function is called at the exit of each function
 * The call is generated by the NEC SX compilers
 */

void
_ftrace_exit2_( void )
{
    if ( scorep_compiler_finalized )
    {
        return;
    }

    char* region_name = scorep_ftrace_getname();
    long  key         = ( long )region_name;

    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "call function exit!!!" );
    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, " ftrace exit 2 %i", key );
    scorep_compiler_hash_node* hash_node = scorep_compiler_hash_get( key );
    if ( hash_node )
    {
        if ( hash_node->region_handle != SCOREP_FILTERED_REGION )
        {
            SCOREP_ExitRegion( hash_node->region_handle );
        }
    }
}

/*
 * This function is called at the exit of the program
 * The call is generated by the NEC SX compilers
 */
void
_ftrace_stop2_( void )
{
    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, " ftrace stop 2" );
}

SCOREP_ErrorCode
scorep_compiler_init_adapter( void )
{
    if ( scorep_compiler_initialize )
    {
        UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER,
                            " inititialize ftrace compiler adapter!" );

        /* Initialize region mutex */
        SCOREP_MutexCreate( &scorep_compiler_region_mutex );

        /* Initialize hash table */
        scorep_compiler_hash_init();

        /* Set flag */
        scorep_compiler_initialize = 0;
    }

    return SCOREP_SUCCESS;
}

SCOREP_ErrorCode
scorep_compiler_init_location( SCOREP_Location* locationData )
{
    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "ftrace Compiler adapter init location!" );
    return SCOREP_SUCCESS;
}

/* Location finalization */
void
scorep_compiler_finalize_location( SCOREP_Location* locationData )
{
    UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, "ftrace compiler adapter finalize location!" );
}

void
scorep_compiler_finalize( void )
{
    /* call only, if previously initialized */
    if ( !scorep_compiler_initialize )
    {
        /* Delete hash table */
        scorep_compiler_hash_free();

        scorep_compiler_initialize = 1;
        scorep_compiler_finalized  = 1;
        UTILS_DEBUG_PRINTF( SCOREP_DEBUG_COMPILER, " finalize ftrace compiler adapter!" );

        /* Delete region mutex */
        SCOREP_MutexDestroy( &scorep_compiler_region_mutex );
    }
}
