/*
 * This file is part of the SILC project (http://www.silc.de)
 *
 * Copyright (c) 2009-2011,
 *    RWTH Aachen, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


/**
 * @ file      SILC_compiler_ibm.c
 * @maintainer Rene Jaekel <rene.jaekel@tu-dresden.de>
 *
 * @brief Support for XL IBM-Compiler
 * Will be triggered by the frunctrion trace option by the xl
 * compiler.
 */

#include <stdio.h>


#include <SILC_Utils.h>
#include <SILC_Events.h>
#include <SILC_Definitions.h>
#include <SILC_RuntimeManagement.h>

#include <SILC_Compiler_Init.h>
#include <SILC_Compiler_Data.h>



static int xl_init = 1;


void
xl_finalize( void );
void
__func_trace_enter( char* name,
                    char* fname,
                    int   lno );
void
__func_trace_exit( char* name,
                   char* fname,
                   int   lno );

/*
 * finalize instrumentation interface
 */
void
silc_xl_free()
{
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, "finalize the gnu compiler instrumentation." );
    hash_free();
    /* set ibm compiler init status to one - means not initialized */
    xl_init = 1;
}

/*
 * This function is called at the entry of each function
 * The call is generated by the IBM xl compilers
 */
void
__func_trace_enter( char* name,
                    char* fname,
                    int   lno )
{
    HashNode* hn;

    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " function name: %s %s", name, fname );

    if ( xl_init )
    {
        SILC_InitMeasurement();
        silc_xl_free();
    }

    /* put function to list */
    if ( ( hn = hash_get( ( long )name ) ) == 0 )
    {
        hash_put( ( long )name, name, fname, lno );
        SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " number %ld and put name -- %s -- to list", ( long )name, name );
    }
    else
    {
        if ( ( hn->reghandle == SILC_INVALID_REGION ) )
        {
            silc_compiler_register_region( hn );
        }
    }
}

/*
 * This function is called at the exit of each function
 * The call is generated by the IBM xl compilers
 */
void
__func_trace_exit( char* name,
                   char* fname,
                   int   lno )
{
    printf( "call function -- %s -- at exit!!!\n", name );
    HashNode* hn;
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, "call function exit!!!" );
    if ( hn = hash_get( ( long )name ) )
    {
        SILC_ExitRegion( hn->reghandle );
    }
}
