/*
 * This file is part of the SILC project (http://www.silc.de)
 *
 * Copyright (c) 2009-2011,
 *    RWTH Aachen, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


/**
 * @ file SILC_compiler_ftrace.c
 *
 * @brief Support for FTrace-Compiler
 * Will be triggered by the '-ftrace' flag of the FTrace
 * compiler.
 */

#include "stdio.h"

#include <SILC_Utils.h>
#include <SILC_Events.h>
#include <SILC_Definitions.h>
#include <SILC_RuntimeManagement.h>


static int necsx_init = 1;

/**
 * @brief Simple hash table to map function names to region identifier
 *
 */
typedef struct HashNode
{
    long              id;            /* hash code (address of function name) */
    SILC_RegionHandle reghandle;     /* associated region identifier  */
    struct HashNode*  next;
} HashNode;

#define HASH_MAX 1021

static HashNode* htab[ HASH_MAX ];

/**
 * Stores region identifier `e' under hash code `h'
 */
static
void
hash_put
(
    long     h,
    uint32_t e
)
{
    long      id  = h % HASH_MAX;
    HashNode* add = ( HashNode* )malloc( sizeof( HashNode ) );
    add->id        = h;
    add->reghandle = e;
    add->next      = htab[ id ];
    htab[ id ]     = add;
}


/**
 * Lookup hash code `h'
 * Returns region identifier if already stored, otherwise VT_NO_ID
 */
/* could also be a region handle return value */
/* is there a 'zero' == invalid return value */
static
SILC_RegionHandle
hash_get
(
    long h
)
{
    long      id   = h % HASH_MAX;
    HashNode* curr = htab[ id ];
    while ( curr )
    {
        if ( curr->id == h )
        {
            return curr->reghandle;
        }
        curr = curr->next;
    }
    return 0;
}

/**
 * Register new region
 */
static uint32_t
register_region( char* func,
                 int   len )
{
    uint32_t rid;

    printf( " register a new region \n" );

    //  hash_put((long) func, rid);
    return rid;
}

void
ftrace_finalize( void );
void
_ftrace_enter2_( void );
void
_ftrace_exit2_( void );
void
_ftrace_stop2_( void );


/**
 * Finalize instrumentation interface
 */
void
ftrace_finalize()
{
    int i;

    for ( i = 0; i < HASH_MAX; i++ )
    {
        if ( htab[ i ] )
        {
            free( htab[ i ] );
            htab[ i ] = NULL;
        }
    }
    necsx_init = 1;
}

/**
 * This function is called at the entry of each function
 * The call is generated by the NEC SX compilers
 */

void
_ftrace_enter2_
(
)
{
    printf( " reached ftrace enter2 \n" );
}

/**
 * This function is called at the exit of each function and generated
 * by the NEC SX compiler.
 **/
void
_ftrace_exit2_
(
)
{
    printf( " reached ftrace exit2 \n" );
}


/**
 * This function is called at the exit of the program and generated
 * by the NEC SX compiler.
 */
void
_ftrace_stop2_
(
)
{
    /*   SILC_FinalizeMeasurement();  */
}
