/*
 * This file is part of the SILC project (http://www.silc.de)
 *
 * Copyright (c) 2009-2011,
 *    RWTH Aachen, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


/**
 * @ file      SILC_compiler_ibm.c
 * @maintainer Rene Jaekel <rene.jaekel@tu-dresden.de>
 *
 * @brief Support for XL IBM-Compiler
 * Will be triggered by the frunctrion trace option by the xl
 * compiler.
 */

#include <stdio.h>

#include <SILC_Utils.h>
#include <SILC_Events.h>
#include <SILC_Definitions.h>
#include <SILC_RuntimeManagement.h>

#include <SILC_Compiler_Init.h>
#include <SILC_Compiler_Data.h>



static int xl_init = 1;

/**
 * data structure to map function name and region identifier
 */


/*
 * register new region
 */
void
silc_xl_register_region
(
)
{
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " register a region: \n" );
}


void
xl_finalize( void );
void
__func_trace_enter( char* name,
                    char* fname,
                    int   lno );
void
__func_trace_exit( char* name,
                   char* fname,
                   int   lno );

/*
 * finalize instrumentation interface
 */
void
xl_finalize()
{
}

/*
 * This function is called at the entry of each function
 * The call is generated by the IBM xl compilers
 */
void
__func_trace_enter( char* name,
                    char* fname,
                    int   lno )
{
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " function name: %s %s \n", name, fname );
}

/*
 * This function is called at the exit of each function
 * The call is generated by the IBM xl compilers
 */
void
__func_trace_exit( char* name,
                   char* fname,
                   int   lno )
{
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, "call function %s at exit!!!\n", fname );
}
