/*
 * This file is part of the SILC project (http://www.silc.de)
 *
 * Copyright (c) 2009-2011,
 *    RWTH Aachen, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


/**
 * @ file      SILC_compiler_ibm.c
 * @maintainer Rene Jaekel <rene.jaekel@tu-dresden.de>
 *
 * @brief Support for XL IBM-Compiler
 * Will be triggered by the frunctrion trace option by the xl
 * compiler.
 */

#include <stdio.h>


#include <SILC_Utils.h>
#include <SILC_Events.h>
#include <SILC_Definitions.h>
#include <SILC_RuntimeManagement.h>

#include <SILC_Compiler_Init.h>
#include <SILC_Compiler_Data.h>



static int silc_compiler_initialize = 1;


void
xl_finalize( void );
void
__func_trace_enter( char* name,
                    char* fname,
                    int   lno );
void
__func_trace_exit( char* name,
                   char* fname,
                   int   lno );

/*
 * @ brief This function is called at the entry of each function.
 * The call is generated by the IBM xl compilers
 *
 * @ param name   function name
 * @ param fname  file name
 * @ param lno    line number
 */
void
__func_trace_enter( char* name,
                    char* fname,
                    int   lno )
{
    HashNode* hn;

    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " function name: %s %s", name, fname );

    if ( silc_compiler_initialize )
    {
        SILC_InitMeasurement();
    }

    /* put function to list */
    if ( ( hn = hash_get( ( long )name ) ) == 0 )
    {
        hash_put( ( long )name, name, fname, lno );
        SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " number %ld and put name -- %s -- to list", ( long )name, name );
    }
    else
    {
        if ( ( hn->reghandle == SILC_INVALID_REGION ) )
        {
            silc_compiler_register_region( hn );
        }
    }
}

/*
 * @ brief This function is called at the exit of each function.
 * The call is generated by the IBM xl compilers
 *
 * @ param name   function name
 * @ param fname  file name
 * @ param lno    line number
 */
void
__func_trace_exit( char* name,
                   char* fname,
                   int   lno )
{
    printf( "call function -- %s -- at exit!!!\n", name );
    HashNode* hn;
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, "call function exit!!!" );
    if ( hn = hash_get( ( long )name ) )
    {
        SILC_ExitRegion( hn->reghandle );
    }
}

SILC_Error_Code
silc_compiler_init_adapter()
{
    if ( silc_compiler_initialize )
    {
        SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER,
                           " inititialize IBM xl compiler adapter!" );

        /* Initialize hash table */
        hash_init();

        /* Sez flag */
        silc_compiler_initialize = 0;
    }

    return SILC_SUCCESS;
}

void
silc_compiler_finalize()
{
    /* call only, if previously initialized */
    if ( !silc_compiler_initialize )
    {
        /* Delete hash table */
        hash_free();

        silc_compiler_initialize = 1;
        SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " finalize IBM xl compiler adapter!" );
    }
}
