/**
 * @ file SILC_compiler_gnu.c
 *
 * @brief Support for GNU-Compiler
 * Will be triggered by the '-finstrument-functions' flag of the GNU
 * compiler.
 */

#include "stdio.h"
#include <SILC_Utils.h>



/**
 * @brief Hash table to map function addresses to region identifier
 */
typedef struct HN
{
    long        id;    /* hash code (address of function) */
    const char* name;  /* associated function name        */
    const char* fname; /*            file name            */
    int         lno;   /*            line number          */
    uint32_t    regid; /* associated region identifier    */
    struct HN*  next;
} HashNode;


/** @brief terminate GNU interface
 *
 */
void
silc_gnu_finalize
(
    void
)
{
    printf( "finalize the gnu compiler instrumentation. \n" );
}


/**@brief
 * This function is called just after the entry of a function
 * generated by the GNU compiler.
 * @param func      The address of the start of the current function.
 * @param callsice  The call site of the current function.
 */
void
__cyg_profile_func_enter
(
    void* func,
    void* callsite
)
{
    printf( "call at function enter!!!\n" );
}

/**
 * This function is called just before the exit of a function
 * generated by the GNU compiler.
 * @param func      The address of the end of the current function.
 * @param callsice  The call site of the current function.
 */
void
__cyg_profile_func_exit
(
    void* func,
    void* callsite
)
{
    printf( "call function exit!!!\n" );
}
