/*
 * This file is part of the SILC project (http://www.silc.de)
 *
 * Copyright (c) 2009-2011,
 *    RWTH Aachen, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


/**
 * @ file SILC_compiler_gnu.c
 *
 * @brief Support for GNU-Compiler
 * Will be triggered by the '-finstrument-functions' flag of the GNU
 * compiler.
 */

#include "stdio.h"

#include <SILC_Utils.h>
#include <SILC_Events.h>
#include <SILC_Definitions.h>
#include <SILC_RuntimeManagement.h>

/**
 * @brief Hash table to map function addresses to region identifier
 */
typedef struct HashNode
{
    long              id;           /* hash code (address of function) */
    const char*       name;         /* associated function name        */
    const char*       fname;        /*            file name            */
    SILC_LineNo       lnobegin;     /*            line number  of begin        */
    SILC_LineNo       lnoend;       /*            line number  of end        */
    SILC_RegionHandle reghandle;    /* region identifier    */
    struct HN*        next;
} HashNode;

#define HASH_MAX 1021

static HashNode* htab[ HASH_MAX ];


static HashNode*
hash_get( long h )
{
    long id = h % HASH_MAX;

    printf( " hash id %i: ", id );

    HashNode* curr = htab[ id ];
    while ( curr )
    {
        if ( curr->id == h )
        {
            return curr;
        }
        curr = curr->next;
    }
    return NULL;
}


/**
 * @brief Register a new region to the measuremnt system
 *
 * @param hn   Hash node which stores the registered regions
 */
static void
register_region
(
    HashNode* hn
)
{
    SILC_SourceFileHandle handle;
    SILC_LineNo           begin, end;
    SILC_AdapterType      adapter = SILC_ADAPTER_COMPILER;
    SILC_RegionType       region  = SILC_REGION_FUNCTION;

    hn->reghandle = SILC_DefineRegion( hn->name, handle, begin, end, adapter, region );

    printf( " register a region: \n" );
}

/**
 * @brief finalize GNU interface
 */
void
silc_gnu_finalize
(
    void
)
{
    printf( "finalize the gnu compiler instrumentation. \n" );

    int i;

    for ( i = 0; i < HASH_MAX; i++ )
    {
        if ( htab[ i ] )
        {
            free( htab[ i ] );
            htab[ i ] = NULL;
        }
    }
}


/**
 * @brief This function is called just after the entry of a function
 * generated by the GNU compiler.
 * @param func      The address of the start of the current function.
 * @param callsice  The call site of the current function.
 */
void
__cyg_profile_func_enter
(
    void* func,
    void* callsite
)
{
    HashNode* hn;
    printf( "call at function enter!!!\n" );


    /*
     * init measurement just for dummy purpose
     *
     * put hash table entries via mechanism for bfd symbol table
     * to calculate function addresses
     */

    SILC_InitMeasurement();

    SILC_RegionHandle SILC_NO_REGION = 0;

    printf( " function pointer: %i \n", ( long )func );

    if ( ( hn = hash_get( ( long )func ) ) )
    {
        if ( hn->reghandle == SILC_NO_REGION )
        {
            /* -- region entered the first time, register region -- */
            register_region( hn );
            printf( " register region with handle %i \n", hn->reghandle );
        }
        printf( "enter the region with handle %i \n", hn->reghandle );
        SILC_EnterRegion( hn->reghandle );
    }
    else
    {
        SILC_RegionHandle dummy = 1;
        SILC_EnterRegion( dummy );
    }
}

/**
 * @brief This function is called just before the exit of a function
 * generated by the GNU compiler.
 * @param func      The address of the end of the current function.
 * @param callsice  The call site of the current function.
 */
void
__cyg_profile_func_exit
(
    void* func,
    void* callsite
)
{
    HashNode* hn;
    printf( "call function exit!!!\n" );
    if ( hn = hash_get( ( long )func ) )
    {
        SILC_ExitRegion( hn->reghandle );
    }
    else
    {
        SILC_RegionHandle dummy = 1;
        SILC_ExitRegion( dummy );
    }
}
