/*
 * This file is part of the SILC project (http://www.silc.de)
 *
 * Copyright (c) 2009-2011,
 *    RWTH Aachen, Germany
 *    Gesellschaft fuer numerische Simulation mbH Braunschweig, Germany
 *    Technische Universitaet Dresden, Germany
 *    University of Oregon, Eugene USA
 *    Forschungszentrum Juelich GmbH, Germany
 *    Technische Universitaet Muenchen, Germany
 *
 * See the COPYING file in the package base directory for details.
 *
 */


/**
 * @file       silc_compiler_ftrace.c
 * @maintainer Daniel Lorenz <d.lorenz@fz-juelich.de>
 *
 * @brief Compiler adapter version for NEC SX compiler
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <SILC_Utils.h>
#include <SILC_Events.h>
#include <SILC_Definitions.h>
#include <SILC_RuntimeManagement.h>

#include <SILC_Compiler_Init.h>
#include <silc_compiler_data.h>


extern void*
silc_ftrace_getname( void );
extern int
silc_ftrace_getname_len( void );


static uint32_t silc_compiler_initialize = 1;


void
_ftrace_enter2_( void );
void
_ftrace_exit2_( void );
void
_ftrace_stop2_( void );

/*
 * This function is called at the entry of each function
 * The call is generated by the NEC SX compilers
 */

void
_ftrace_enter2_()
{
    char*                    region_name = silc_ftrace_getname();
    int                      name_len    = silc_ftrace_getname_len();

    silc_compiler_hash_node* hash_node = silc_compiler_hash_get( ( long )region_name );

    if ( silc_compiler_initialize )
    {
        /* not initialized so far */
        SILC_InitMeasurement();
    }

    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, "function name: %s \n", region_name );
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, "function length: %i \n", name_len );

    if ( !hash_node )
    {
        silc_compiler_hash_put( ( long )region_name, region_name, "", name_len );
    }

    if ( ( hash_node = silc_compiler_hash_get( ( long )region_name ) ) )
    {
        if ( hash_node->reghandle == SILC_INVALID_REGION )
        {
            /* -- region entered the first time, register region -- */
            silc_compiler_register_region( hash_node );
        }
        SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER,
                           "enter the region with handle %i \n",
                           hash_node->region_handle );
        SILC_EnterRegion( hash_node->region_handle );
    }
}


/*
 * This function is called at the exit of each function
 * The call is generated by the NEC SX compilers
 */

void
_ftrace_exit2_()
{
    char*                    region_name = silc_ftrace_getname();
    long                     key         = ( long )region_name;
    silc_compiler_hash_node* hash_node;

    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, "call function exit!!!\n" );
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " ftrace exit 2 \t %i \n", key );
    if ( hash_node = silc_compiler_hash_get( key ) )
    {
        SILC_ExitRegion( hash_node->region_handle );
    }
}

/*
 * This function is called at the exit of the program
 * The call is generated by the NEC SX compilers
 */
void
_ftrace_stop2_()
{
    SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " ftrace stop 2 \n" );
}

SILC_Error_Code
silc_compiler_init_adapter()
{
    if ( silc_compiler_initialize )
    {
        SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER,
                           " inititialize ftrace compiler adapter!" );

        /* Initialize hash table */
        silc_compiler_hash_init();

        /* Sez flag */
        silc_compiler_initialize = 0;
    }

    return SILC_SUCCESS;
}

void
silc_compiler_finalize()
{
    /* call only, if previously initialized */
    if ( !silc_compiler_initialize )
    {
        /* Delete hash table */
        silc_compiler_hash_free();

        silc_compiler_initialize = 1;
        SILC_DEBUG_PRINTF( SILC_DEBUG_COMPILER, " finalize ftrace compiler adapter!" );
    }
}
