#!/bin/sh

REPOS="$1"
TXN="$2"

#### Log message check: begin ##################################################
# Log message must contain some text

# log is pre-populated by hook multiplexer
if [ ! -s log ]; then
    echo "Commit rejected: Please provide a meaningful commit message and try again." 1>&2
    exit 1
fi
#### Log message check: end ####################################################
