#!/bin/sh

# NAME
#     beautify
#
# DESCRIPTION
#     Beautify all modified and added source files in your working copy.
#     Without beautification, a commit may be rejected. Currently, the
#     beautification is performed by "uncrustify" using the configuration
#     file "common/beautifier/beautify.cfg".
#
#
# USAGE
#     Call beautify from anywhere in your working copy by relative path.
#
# AUTHORS
#     Christian Feld <c.feld@fz-juelich.de>
#     Markus Geimer <m.geimer@fz-juelich.de>
#     Bert Wesarg <bert.wesarg@tu-dresden.de>

set -e

argv0=${0##*/}
BEAUTIFY_ROOT=${0%/*}
: ${BEAUTIFY_ROOT:=.}
BEAUTIFY_ROOT=$(cd $BEAUTIFY_ROOT && pwd)

SUBDIRECTORY_OK=Yes
. $(git --exec-path)/git-sh-setup
require_work_tree
cd_to_toplevel

# Setup and use common beautification code
: ${BEAUTIFY_CONFIG:=$BEAUTIFY_ROOT/beautify.cfg}
if [ ! -f $BEAUTIFY_ROOT/beautify-common ]
then
    echo "  ERROR    Could not find $BEAUTIFY_ROOT/beautify-common"
    exit 1
fi
. $BEAUTIFY_ROOT/beautify-common

# Iterate over candidate files in the index and the working copy, modifies
# the working copy
(
    eval git diff-files --name-only --ignore-submodules               -- $extensions
    eval git diff-index --name-only --ignore-submodules --cached HEAD -- $extensions
) | sort -u |
while read path
do
    beautify_candidate "$path"
done
